### ISSUE TITLE
Update css - monsters

### ISSUE THREAD

**Issue by capelastegui** [capelastegui/sfrpg#41]
Change list:
- Integrate monster css into default css
- in .monsterClass reduce margin-bottom
- Consider columns

Add css elements:
```css 
.monsterList {
  -moz-column-count: 2;
  -webkit-column-count: 2;
  column-count: 2;  
  -moz-column-rule-style: none;
  -webkit-column-rule-style: none;
  column-rule-style: none;
  column-width: 300px;
  /*width: 900px;*/
  /*width: 20cm;*/

}
```

**Comment by capelastegui** [comment]
To integrate monster css, need to add a monster-specific class to the following items:

```css 
table, td, th {  
  border: 1px solid black;
  border-collapse: collapse;  
  border-color: #003300;  
  text-align: center;
}



td.title {  
  font-weight: bold;  
  background-color: #003300;  
  color: white;  

}

td.subtitle {  
  background-color: #73c173;  
  font-weight: bold;
height: 12px;  
}
```
